/*
 * This file was automatically generated by EvoSuite
 * Wed Aug 09 04:29:57 GMT 2017
 */

package calendar;

import org.junit.Test;
import static org.junit.Assert.*;
import calendar.DateOutOfRangeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DateOutOfRangeException_ESTest extends DateOutOfRangeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DateOutOfRangeException dateOutOfRangeException0 = new DateOutOfRangeException(":<y~';Z{Z<U$Jp");
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      DateOutOfRangeException dateOutOfRangeException0 = new DateOutOfRangeException();
  }
}
